### ISSUE TITLE
Manage versions of this github action using a helper action

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/action-major-minor-tag-calculator#59]
We have made use of [Actions-R-Us/actions-tagger](https://github.com/Actions-R-Us/actions-tagger). @manics since it has been working great and for consistency, agree to add such workflow to this repo as well?

I figure we then just copy the following pretty much: https://github.com/jupyterhub/action-k8s-namespace-report/blob/main/.github/workflows/release-updates.yaml

**Comment by manics** [comment]
Sounds good to me!
